#ifndef GUARD_CONSTANTS_BERRY_H
#define GUARD_CONSTANTS_BERRY_H

#define BERRY_NONE 0

enum BerryFirmness
{
    BERRY_FIRMNESS_UNKNOWN,
    BERRY_FIRMNESS_VERY_SOFT,
    BERRY_FIRMNESS_SOFT,
    BERRY_FIRMNESS_HARD,
    BERRY_FIRMNESS_VERY_HARD,
    BERRY_FIRMNESS_SUPER_HARD,
};

enum BerryColor
{
    BERRY_COLOR_RED,
    BERRY_COLOR_BLUE,
    BERRY_COLOR_PURPLE,
    BERRY_COLOR_GREEN,
    BERRY_COLOR_YELLOW,
    BERRY_COLOR_PINK,
};

enum __attribute__((__packed__)) Flavor
{
    FLAVOR_SPICY,
    FLAVOR_DRY,
    FLAVOR_SWEET,
    FLAVOR_BITTER,
    FLAVOR_SOUR,
    FLAVOR_COUNT,
};

#define BERRY_STAGE_NO_BERRY    0  // there is no tree planted and the soil is completely flat.
#define BERRY_STAGE_PLANTED     1
#define BERRY_STAGE_SPROUTED    2
#define BERRY_STAGE_TALLER      3
#define BERRY_STAGE_FLOWERING   4
#define BERRY_STAGE_BERRIES     5
#define BERRY_STAGE_TRUNK       6 // These follow BERRY_STAGE_BERRIES to preserve save compatibility
#define BERRY_STAGE_BUDDING     7
#define BERRY_STAGE_SPARKLING   255

// Berries can be watered in the following stages:
// - BERRY_STAGE_PLANTED
// - BERRY_STAGE_SPROUTED
// - BERRY_STAGE_TALLER
// - BERRY_STAGE_FLOWERING
#define NUM_WATER_STAGES 4

// IDs for berry tree objects, indexes into berryTrees in SaveBlock1
// Named for whatever berry is initially planted there on a new game
// Those with no initial berry are named "soil"
#define BERRY_TREE_ROUTE_102_PECHA        1
#define BERRY_TREE_ROUTE_102_ORAN_1       2
#define BERRY_TREE_ROUTE_102_ORAN_2       3
#define BERRY_TREE_ROUTE_103_CHERI_1      4
#define BERRY_TREE_ROUTE_103_LEPPA        5
#define BERRY_TREE_ROUTE_103_CHERI_2      6
#define BERRY_TREE_ROUTE_104_SOIL_1       7
#define BERRY_TREE_ROUTE_104_ORAN_1       8
#define BERRY_TREE_ROUTE_104_CHERI_1      9
#define BERRY_TREE_ROUTE_104_SOIL_2       10
#define BERRY_TREE_ROUTE_104_LEPPA        11
#define BERRY_TREE_ROUTE_104_ORAN_2       12
#define BERRY_TREE_ROUTE_104_SOIL_3       13
#define BERRY_TREE_ROUTE_104_PECHA        14
#define BERRY_TREE_ROUTE_104_SOIL_4       15
#define BERRY_TREE_ROUTE_104_CHERI_2      16
#define BERRY_TREE_ROUTE_110_NANAB_1      17
#define BERRY_TREE_ROUTE_110_NANAB_2      18
#define BERRY_TREE_ROUTE_110_NANAB_3      19
#define BERRY_TREE_ROUTE_111_RAZZ_1       20
#define BERRY_TREE_ROUTE_111_RAZZ_2       21
#define BERRY_TREE_ROUTE_111_ORAN_1       22
#define BERRY_TREE_ROUTE_111_ORAN_2       23
#define BERRY_TREE_ROUTE_112_RAWST_1      24
#define BERRY_TREE_ROUTE_112_PECHA_1      25
#define BERRY_TREE_ROUTE_112_PECHA_2      26
#define BERRY_TREE_ROUTE_112_RAWST_2      27
#define BERRY_TREE_ROUTE_114_PERSIM_1     28
#define BERRY_TREE_ROUTE_114_PERSIM_2     29
#define BERRY_TREE_ROUTE_114_PERSIM_3     30
#define BERRY_TREE_ROUTE_115_BLUK_1       31
#define BERRY_TREE_ROUTE_115_BLUK_2       32
#define BERRY_TREE_ROUTE_115_KELPSY_1     33
#define BERRY_TREE_ROUTE_115_KELPSY_2     34
#define BERRY_TREE_ROUTE_115_HABAN_1      35
#define BERRY_TREE_ROUTE_115_HABAN_2      36
#define BERRY_TREE_ROUTE_116_PINAP_1      37
#define BERRY_TREE_ROUTE_116_CHESTO_1     38
#define BERRY_TREE_ROUTE_116_CHESTO_2     39
#define BERRY_TREE_ROUTE_116_PINAP_2      40
#define BERRY_TREE_ROUTE_117_WEPEAR_1     41
#define BERRY_TREE_ROUTE_117_WEPEAR_2     42
#define BERRY_TREE_ROUTE_117_WEPEAR_3     43
#define BERRY_TREE_ROUTE_118_SITRUS_1     44
#define BERRY_TREE_ROUTE_118_SOIL         45
#define BERRY_TREE_ROUTE_118_SITRUS_2     46
#define BERRY_TREE_ROUTE_119_POMEG        47
#define BERRY_TREE_ROUTE_119_JABOCA       48
#define BERRY_TREE_ROUTE_119_ROWAP        49
#define BERRY_TREE_ROUTE_119_HONDEW_1     50
#define BERRY_TREE_ROUTE_119_HONDEW_2     51
#define BERRY_TREE_ROUTE_119_SITRUS       52
#define BERRY_TREE_ROUTE_119_LEPPA        53
#define BERRY_TREE_ROUTE_119_MICLE        54
#define BERRY_TREE_ROUTE_120_ASPEAR_1     55
#define BERRY_TREE_ROUTE_120_ASPEAR_2     56
#define BERRY_TREE_ROUTE_120_PECHA_1      57
#define BERRY_TREE_ROUTE_120_PECHA_2      58
#define BERRY_TREE_ROUTE_120_COBA         59
#define BERRY_TREE_ROUTE_120_CHARTI       60
#define BERRY_TREE_ROUTE_120_RAZZ         61
#define BERRY_TREE_ROUTE_120_NANAB        62
#define BERRY_TREE_ROUTE_120_PINAP        63
#define BERRY_TREE_ROUTE_120_WEPEAR       64
#define BERRY_TREE_ROUTE_121_PERSIM       65
#define BERRY_TREE_ROUTE_121_ASPEAR       66
#define BERRY_TREE_ROUTE_121_RAWST        67
#define BERRY_TREE_ROUTE_121_CHESTO       68
#define BERRY_TREE_ROUTE_121_SOIL_1       69
#define BERRY_TREE_ROUTE_121_NANAB_1      70
#define BERRY_TREE_ROUTE_121_NANAB_2      71
#define BERRY_TREE_ROUTE_121_SOIL_2       72
#define BERRY_TREE_ROUTE_121_OCCA         73
#define BERRY_TREE_ROUTE_121_PASSHO       74
#define BERRY_TREE_ROUTE_121_RINDO        75
#define BERRY_TREE_ROUTE_121_WACAN        76
#define BERRY_TREE_ROUTE_123_QUALOT_1     77
#define BERRY_TREE_ROUTE_123_POMEG_1      78
#define BERRY_TREE_ROUTE_123_POMEG_2      79
#define BERRY_TREE_ROUTE_123_POMEG_3      80
#define BERRY_TREE_ROUTE_123_POMEG_4      81
#define BERRY_TREE_ROUTE_123_GREPA_1      82
#define BERRY_TREE_ROUTE_123_GREPA_2      83
#define BERRY_TREE_ROUTE_123_LEPPA_1      84
#define BERRY_TREE_ROUTE_123_SOIL         85
#define BERRY_TREE_ROUTE_123_LEPPA_2      86
#define BERRY_TREE_ROUTE_123_GREPA_3      87
#define BERRY_TREE_ROUTE_123_GREPA_4      88
#define BERRY_TREE_ROUTE_123_QUALOT_2     89
#define BERRY_TREE_ROUTE_123_QUALOT_3     90
#define BERRY_TREE_ROUTE_123_QUALOT_4     91
#define BERRY_TREE_ROUTE_123_PECHA        92
#define BERRY_TREE_ROUTE_123_SITRUS       93
#define BERRY_TREE_ROUTE_123_RAWST        94
#define BERRY_TREE_ROUTE_123_KEIBA        95
#define BERRY_TREE_ROUTE_123_PAYAPA       96
#define BERRY_TREE_ROUTE_123_TANGA        97
#define BERRY_TREE_ROUTE_123_ROSELI       98
#define BERRY_TREE_ROUTE_123_SHUCA        99
#define BERRY_TREE_ROUTE_123_BABIRI       100
#define BERRY_TREE_ROUTE_123_CHILAN       101
#define BERRY_TREE_ROUTE_130_LIECHI       102
#define BERRY_TREE_LILYCOVE_SALAC_1       103
#define BERRY_TREE_LILYCOVE_CUSTAP        104
#define BERRY_TREE_LILYCOVE_SALAC_2       105
#define BERRY_TREE_MOSSDEEP_LIECHI        106
#define BERRY_TREE_MOSSDEEP_PETAYA        107
#define BERRY_TREE_MOSSDEEP_KEE           108
#define BERRY_TREE_MOSSDEEP_MARANGA       109
#define BERRY_TREE_MT_PYRE_KASIB_1        110
#define BERRY_TREE_MT_PYRE_KASIB_2        111
#define BERRY_TREE_SOOTOPOLIS_PASSHO_1    112
#define BERRY_TREE_SOOTOPOLIS_PASSHO_2    113
#define BERRY_TREE_SOOTOPOLIS_GANLON      114
#define BERRY_TREE_SOOTOPOLIS_APICOT      115
#define BERRY_TREE_SOOTOPOLIS_LANSAT      116
#define BERRY_TREE_EVER_GRANDE_CHILAN     117
#define BERRY_TREE_EVER_GRANDE_ENIGMA_1   118
#define BERRY_TREE_EVER_GRANDE_ENIGMA_2   119
#define BERRY_TREE_EVER_GRANDE_SALAC      120
#define BERRY_TREE_EVER_GRANDE_LIECHI     121
#define BERRY_TREE_EVER_GRANDE_PETAYA     122
#define BERRY_TREE_OBSIDIAN_SHORES_COLBUR 123
#define BERRY_TREE_OBSIDIAN_SHORES_STARF  124
#define BERRY_TREE_OBSIDIAN_SHORES_CHILAN 125


// Remainder are unused

#define BERRY_TREES_COUNT 128

#endif // GUARD_CONSTANTS_BERRY_H
